# Generated by Django 2.1.2 on 2018-10-20 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=3500, null=True)),
                ('version', models.IntegerField()),
                ('createdBy', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_document_created_by', to=settings.AUTH_USER_MODEL)),
                ('editingBy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_document_editing_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
